[package]
name = "b"
version = "0.1.0"
authors = ["Alexander Komarov <ak@akxcv.com>"]
edition = "2018"

[dependencies]
clap = "2.32.0"
dirs = "1.0"
skim = "0.5.2"
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.8"
